### ISSUE TITLE
Set DNS for GitHub pages

### ISSUE THREAD

**Issue by chmac** [TripSit/comboapp#13]
I've built and deployed the app to GitHub pages. You can see the latest version [here](https://github.com/TripSit/comboapp/tree/gh-pages).

But, it's not so easy to test this. By default the GitHub pages site would be https://tripsit.github.io/comboapp/. But I created a `CNAME` file as part of the deploy. GitHub reads this, and then thinks the site is deployed at that domain. I've specified `combo.tripsit.me` as the value.

However, the issue arises as follows. When you try to load the GitHub pages site, you should get a 301 redirect to the `combo.tripsit.me` domain. But, that domain isn't yet pointing to the GitHub pages site, so you can't really test it.

My suggestion is to just delete the current A record for `combo.tripsit.me` and create a new CNAME record that points to `tripsit.github.io`. Once that change is live on the DNS servers, then we should be hosted on the new GitHub pages site.

To deploy the site, you can do something like:

- `cd app/`
- `nvm use`
- `yarn`
- `yarn deploy`

But as I said, I've already done that to make sure it works. So it's only necessary if you want to deploy new changes. I've also updated the README a bit in #12 to make all this a little clearer in the future.

**Comment by LunaUrsa** [comment]
Thanks a ton, taking a look right now

**Comment by LunaUrsa** [comment]
~It's up! Looks like that was easy, thanks so much!~

~I spoke too soon, it seems like there's an SSL issue with this method, I'm taking a look~

~Okay, I think I'm just not familiar with how this is supposed to work: I have the DNS setup and for testing we can use the "newcombo" subdomain. The domain works, SSL works, but it's pulling up the readme file. I know you said to deploy with yarn, but I'm not sure how to do that via the repository? Is that something you want me to do on the server? I'm missing something basic here, please bare with me while I learn this. Im not giving up, still searching atm~

I think I got it! I had to set up the Pages settings for the repo, point to the right branch, and wait for the action to finish, but now it works with SSL even after clearing the cache. I think we may be good here, and this is going to be super helpful in the future

**Comment by chmac** [comment]
@LunaUrsa Ah, you setup an auto deploy GitHub action? That's cool! Makes it super easy to deploy changes.

**Comment by chmac** [comment]
I saw an email with a message about a favicon but don't see that message here on the issue (via the GitHub app).

Did that issue get solved?

**Comment by LunaUrsa** [comment]
I seem to have stumbled upon that cool feature; very nice I agree!

Thanks for the follow-up, forgot about that in my edits: I noticed that the favicon was removed, and now it looks like the page is missing the icon, should that be re-added?

**Comment by chmac** [comment]
Let's track that in a new issue.
