### ISSUE TITLE
SSL cert has expired

### ISSUE THREAD

**Issue by chmac** [TripSit/comboapp#6]
The SSL cert on combos.tripsit.me has expired, it expired 5 Dec 2018. Means the site is not accessible to "typical" users. I guess the letsencrypt certificate is not set for automatic renewal.

I'd be willing to put some time into helping to fix this. It should be a reasonably simple task of setting up the right cronjob to auto renew the certificates. Depends on how the server is setup exactly. I could also take over the hosting of the `combo.tripsit.me` domain if that's helpful as I have a server which does all the letsencrypt stuff automatically.

**Comment by levino** [comment]
How about netlify?

**Comment by chmac** [comment]
@Levino Aloha! Funny to see you on here! :-)

When I hosted the app before @TripSit took it over, I decided against netlify as I imagine some people might consider the content to be a little controversial. Perhaps it's not covered by their terms of service and they'd be a good fit, they certainly make the process easy. I guess it's up to whoever is managing the servers at @TripSit.

**Comment by levino** [comment]
It showed on my Twitter feed...
