### ISSUE TITLE
Wanna add me as a contributor?

### ISSUE THREAD

**Issue by chmac** [TripSit/comboapp#8]
I realise that I'm not a contributor on this repo, so can't manage issues, etc. I'm not really sure how the tripsit crew manages this, if I should create stuff in my upstream fork and then submit PRs (I guess that's possible on GitHub, I've only ever done it the other way), or if it makes sense to add me as a contributor here. I originally planned to transfer the repo, but we hit some roadblocks on that, so a fork was faster.

**Comment by Spacebjorn** [comment]
For now the easiest thing is most likely to fork the repo and submit PR. I can't add you as a contributor myself and ill have to get a hold of the organization owner who is quite busy writing their phd thesis. Apologizes if i seemed rude in the other post. 

Anyways, my current plan is reworking the benzo, dxm and possibly the factsheet repo first. The end goal is to make them into React applications not needing nodejs which was ehh a mistake on my own beginner part. If you want to work on this repo, as i estimate the factsheet one is going to take me a while, feel more than welcome to

**Comment by chmac** [comment]
@Spacebjorn OK, it's a bit finicky, but it looks like I can create PRs from my repo. I created this repo originally, and this one is a fork of mine, so I don't think I can fork from a fork.

I'm not sure how soon I'll get around to working on this, but I wanted to start collecting ideas and resources in the issues, then if / when I get some time, I have a list of tasks ready to go.

**Comment by chmac** [comment]
@LunaUrsa Coming back to this. Would you like to add me as a contributor to this repo? Then if we use GitHub pages for example then I could publish updates, etc.

**Comment by LunaUrsa** [comment]
Bamzo, thanks for the offer, i've given you triage permissions, and this can be expanded as we get to know each other =D
