### ISSUE TITLE
Publishing an alternate and updated version

### ISSUE THREAD

**Issue by chmac** [TripSit/comboapp#9]
Howdy folks,

I originally wrote this app a good while back, and it hasn't been updated since. We had one or two issues with SSL certificates expiring and taking a while to be renewed etc. I've also had a really hard time actually figuring out how, if anybody, I can communicate with at TripSit. I'd be happy to connect with y'all, and to help out keeping the SSL certs renewed, or more like setting it up to auto renew, etc. In the meantime, I'm going to publish another version of the app so that I can roll some updates. I'm also going to (hopefully sometime in the not too distant future!) try to update the data sources.

@Spacebjorn if you're still involved on the TripSit side would be happy to connect directly and see how we might collaborate.

Cheers - Callum.

**Comment by LunaUrsa** [comment]
Hey @chmac Sorry for the delay, stumbled upon this project and appreciate your contributions. 

I welcome you to join the discord and send me (MoonBear) a message: https:discord.gg/tripsit

Happy to talk about the code and much needed updates

**Comment by chmac** [comment]
@LunaUrsa I'm happy to provide some input here, but honestly, after the almost total lack of response over the years, my faith in being able to productively cooperate with tripsit is pretty low.

**Comment by LunaUrsa** [comment]
Understandable, I don't blame you. I'm around now and willing to talk if you are; a lot has changed in the last year. The best way to contact the (very small) team is on discord now.

**Comment by chmac** [comment]
Great. What kind of updates are you thinking about? Wanna open some issues here to start some discussion rolling? I can post a couple, some of the assets are not loaded when offline for example.

**Comment by chmac** [comment]
@LunaUrsa If you want to reach out for a private discussion for any reason, you could reach me @chmac on telegram, twitter, and assorted other channels.

**Comment by LunaUrsa** [comment]
Hey, i sent a friend request on discord, I would love to show you the different development rooms we have going on.

> What kind of updates are you thinking about?

I don't have any specific ideas other than trying to update stuff and get them more stable. I've been learning stuff from scratch to try and re-host things using cloudflare and docker. Im def open to ideas and contributions

**Comment by chmac** [comment]
I'm not very active on discord, and I'm not actually `chmac` there, I just registered `chmac7` with the new username change thing.

**Comment by LunaUrsa** [comment]
I've just sent a friend request to that one, I am moonbear on discord
